// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	sysmon "github.com/Haba1234/sysmon/internal/sysmon"
	mock "github.com/stretchr/testify/mock"
)

// Collector is an autogenerated mock type for the Collector type
type Collector struct {
	mock.Mock
}

// GetStats provides a mock function with given fields: m
func (_m *Collector) GetStats(m int) sysmon.StatisticsData {
	ret := _m.Called(m)

	var r0 sysmon.StatisticsData
	if rf, ok := ret.Get(0).(func(int) sysmon.StatisticsData); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Get(0).(sysmon.StatisticsData)
	}

	return r0
}

// GetStatusServices provides a mock function with given fields:
func (_m *Collector) GetStatusServices() sysmon.StatusServices {
	ret := _m.Called()

	var r0 sysmon.StatusServices
	if rf, ok := ret.Get(0).(func() sysmon.StatusServices); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(sysmon.StatusServices)
	}

	return r0
}

// Start provides a mock function with given fields: ctx
func (_m *Collector) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
