// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	google_golang_orggrpc "google.golang.org/grpc"

	grpc "github.com/Haba1234/sysmon/internal/grpc/api"

	mock "github.com/stretchr/testify/mock"
)

// StatisticsClient is an autogenerated mock type for the StatisticsClient type
type StatisticsClient struct {
	mock.Mock
}

// ListStatistics provides a mock function with given fields: ctx, in, opts
func (_m *StatisticsClient) ListStatistics(ctx context.Context, in *grpc.SubscriptionRequest, opts ...google_golang_orggrpc.CallOption) (grpc.Statistics_ListStatisticsClient, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 grpc.Statistics_ListStatisticsClient
	if rf, ok := ret.Get(0).(func(context.Context, *grpc.SubscriptionRequest, ...google_golang_orggrpc.CallOption) grpc.Statistics_ListStatisticsClient); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(grpc.Statistics_ListStatisticsClient)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *grpc.SubscriptionRequest, ...google_golang_orggrpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
