// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeStatisticsServer is an autogenerated mock type for the UnsafeStatisticsServer type
type UnsafeStatisticsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedStatisticsServer provides a mock function with given fields:
func (_m *UnsafeStatisticsServer) mustEmbedUnimplementedStatisticsServer() {
	_m.Called()
}
