name: sysmon tests

on:
  push:
    branches:
      - sysmon*
      - master

env:
  GO111MODULE: "on"

jobs:
  go_get:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'sysmon') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: go get
        run: cd /tmp && go get -v "github.com/${GITHUB_REPOSITORY}/${BRANCH}@${BRANCH}"

  lint:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'sysmon') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39
          working-directory: ${{ env.BRANCH }}

  tests:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.ref, 'sysmon') }}
    steps:
      - name: Extract branch name
        run: echo "BRANCH=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Unit tests

        run: go test -v -count=100 -race -timeout=1m ./... -coverprofile=coverage.txt -covermode=atomic
        working-directory: ${{ env.BRANCH }}

      - name: Generate coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true


  tests_by_makefile:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'sysmon')
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: make lint
        run: make lint

      - name: make build
        run: make build

      - name: make test
        run: make test