name: tests and build

on:
  pull_request:
  push:
    branches:
      - master

env:
  GO111MODULE: "on"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Linters
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.39

  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ^1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Unit long tests
        run: go test -v -count=10 -race -timeout=5m ./... -coverprofile=coverage1.txt -covermode=atomic

      - name: Unit short tests
        run: go test -short -v -count=100 -race -timeout=5m ./... -coverprofile=coverage2.txt -covermode=atomic

      - name: Integration tests
        run: go test -tags integration -v -race ./tests/integration/... -coverprofile=coverage3.txt -covermode=atomic

      - name: Generate coverage report
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage1.txt,./coverage2.txt,./coverage3.txt
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest ]
    needs: [ lint, tests ]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: make build